name: Check labels action
description: |
  This action runs on PR events and verifies that labels are present/absent according to the provided rules.
inputs:
  one-of:
    description: |
      A CSV list of labels regular expression. Exactly one of them must match the PR labels.
    required: true
  pull-request:
    description: |
      The PR JSON payload, as string. We're only checking for labels, so as long as the labels fields follow the schema
      of PRs as described [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request),
      it'll be all right. It defaults to the pull request payload triggering the event, if the event is a pull_request.
      Otherwise it throws.
    required: false
outputs:
  matched-labels:
    description: |
      A CSV list of labels that have been found on the PR.
runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.one-of }}
