services:
  action:
    image: infra-blocks/github-action-typescript-docker-template
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: github-action-typescript-docker-template
