name: Build Image

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: node-version
        run: |
          echo "node-version=$(cat .nvmrc)" >> "${GITHUB_OUTPUT}"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build, tag and publish docker image
        id: docker-publish
        uses: infrastructure-blocks/docker-publish-action@v1
        env:
          NODE_VERSION: ${{ steps.node-version.outputs.node-version }}
        with:
          service: action
          tags: '["git-sha-${{ github.sha }}"]'
      - name: Show published images
        run: |
          echo "${{ steps.docker-publish.outputs.published }}"
  self-test:
    runs-on: ubuntu-22.04
    needs:
      - build-image
    steps:
      - uses: actions/checkout@v4
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: get-current-pr
        with:
          sha: ${{ github.event.pull_request.head.sha }}
      - uses: jenseng/dynamic-uses@v1
        id: check-label-with-pr-input
        with:
          uses: docker://public.ecr.aws/infrastructure-blocks/check-labels-action:git-sha-${{ github.sha }}
          with: "{\"exactly-once\": \"[\\\"^no version$\\\", \\\"^patch$\\\", \\\"^minor$\\\", \\\"^major$\\\"]\", \"pull-request\": ${{ toJson(steps.get-current-pr.outputs.pr) }}}"
      - run: |
          echo ${{ steps.check-label-with-pr-input.outputs.matched-labels }}
