name: Docker Tag

on:
  push:
    tags:
      - "v**"

# TODO: workflow.
jobs:
  docker-tag:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Parse metadata from docker/docker-compose.yml
        id: metadata
        run: |
          image="$(yq -e '.services["action"].image' docker/docker-compose.yml)"
          repository=$(echo "${image}" | cut -d ':' -f 1)
          echo "repository=${repository}" >> "${GITHUB_OUTPUT}"
          echo "tag=git-sha-${{ github.sha }}" >> "${GITHUB_OUTPUT}"
      - uses: infrastructure-blocks/docker-tag-action@v1
        with:
          image: ${{ steps.metadata.outputs.repository }}:${{ steps.metadata.outputs.tags }}
          tags: '["${{ github.ref_name }}"]'
