name: Docker Tag

on:
  push:
    tags:
      - "v**"

jobs:
  docker-compose-service-metadata:
    permissions:
      contents: read
    uses: infrastructure-blocks/docker-compose-service-metadata-workflow/.github/workflows/docker-compose-service-metadata.yml@v1
    with:
      service: action
  docker-tag:
    permissions:
      id-token: write
    needs:
      - docker-compose-service-metadata
    uses: infrastructure-blocks/aws-ecr-docker-tag-workflow/.github/workflows/aws-ecr-docker-tag.yml@v1
    with:
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      image: ${{ fromJson(needs.docker-compose-service-metadata.outputs.service-metadata).image }}
      tags: '["${{ github.ref_name }}"]'
