name: Docker Tag

on:
  push:
    tags:
      - "v**"

jobs:
  docker-compose-metadata:
    permissions:
      contents: read
    uses: infrastructure-blocks/docker-compose-metadata-workflow/.github/workflows/docker-compose-metadata.yml@v1
  docker-tag:
    permissions:
      id-token: write
    needs:
      - docker-compose-metadata
    uses: infrastructure-blocks/aws-ecr-docker-tag-workflow/.github/workflows/aws-ecr-docker-tag.yml@v1
    with:
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      image: ${{ fromJson(needs.docker-compose-metadata.outputs.metadata).services.action.image }}
      tags: '["${{ github.ref_name }}"]'
