name: Self Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: check-label
        with:
          one-of: no version, patch, minor, major
      - run: |
          echo ${{ steps.check-label.outputs.matched-labels }}
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: get-current-pr
        with:
          sha: ${{ github.event.pull_request.head.sha }}
      - uses: ./
        id: check-label-with-pr-input
        with:
          pull-request: ${{ steps.get-current-pr.outputs.pr }}
          one-of: no version, patch, minor, major
      - run: |
          echo ${{ steps.check-label-with-pr-input.outputs.matched-labels }}
